---
- hosts: all
  gather_facts: false
  tasks:
    - name: 'Hello World Message'
      ansible.builtin.debug:
        msg: "Hello from {{ inventory_hostname }}"

    - name: 'Ping test'
      ansible.builtin.ping: