---
## hosts vars file
## options (provided as a reference, see collection documentation for details)
## - name: required
##   new_name: this will rename a host
##   description:
##   inventory:
##   variables:
##   enabled: default "True"
##   state: default "present"

controller_hosts:
  - name: 'aap_config_linux-01.local.jmb'
    description: "{{ controller_default_description }}"
    inventory: 'aap_config_linux_inventory'
  - name: 'aap_config_linux-02.local.jmb'
    description: "{{ controller_default_description }}"
    inventory: 'aap_config_linux_inventory'
  - name: 'sqlserv2k12.local.jmb'
    description: "{{ controller_default_description }}"
    inventory: 'aap_config_win_inventory'
  - name: 'win10client.local.jmb'
    description: "{{ controller_default_description }}"
    inventory: 'aap_config_win_inventory'
